#!/usr/bin/env node
/**
 * Generates .env.production with random database passwords and secrets.
 * Edit DOMAIN, Google OAuth, and optional R2 before deploying.
 */
import { randomBytes } from 'node:crypto';
import { writeFileSync, existsSync } from 'node:fs';
import { resolve, dirname } from 'node:path';
import { fileURLToPath } from 'node:url';

const root = resolve(dirname(fileURLToPath(import.meta.url)), '..');
const outPath = resolve(root, '.env.production');

function hex(bytes = 32) {
	return randomBytes(bytes).toString('hex');
}

if (existsSync(outPath)) {
	console.error('.env.production already exists. Delete it first or edit manually.');
	process.exit(1);
}

const domain = process.env.DOMAIN ?? 'fjordsend.example.com';
const postgresUser = 'fjordsend';
const postgresPassword = hex(24);
const postgresDb = 'fjordsend';
const jwtSecret = hex(32);
const authSecret = hex(32);

const webUrl = `https://${domain}`;
const apiUrl = `https://api.${domain}`;

const env = `# Generated by: npm run provision
# Edit DOMAIN-related values and Google OAuth before going live.

# --- Public URLs (must match your DNS) ---
DOMAIN=${domain}
API_DOMAIN=api.${domain}
WEB_PUBLIC_URL=${webUrl}
API_PUBLIC_URL=${apiUrl}
PUBLIC_API_URL=${apiUrl}
CORS_ORIGINS=${webUrl}
AUTH_URL=${webUrl}

# Let's Encrypt contact for HTTPS (Caddy)
ACME_EMAIL=you@${domain}

# --- PostgreSQL (Docker creates this user/database) ---
POSTGRES_USER=${postgresUser}
POSTGRES_PASSWORD=${postgresPassword}
POSTGRES_DB=${postgresDb}
DATABASE_DRIVER=postgres
DATABASE_URL=postgresql://${postgresUser}:${postgresPassword}@postgres:5432/${postgresDb}

# --- Redis ---
REDIS_URL=redis://redis:6379

# --- API ---
API_PORT=3001
NODE_ENV=production
JWT_SECRET=${jwtSecret}
STORAGE_DRIVER=local
LOCAL_STORAGE_PATH=/app/apps/api/data/uploads

# Cloudflare R2 (recommended for production — set STORAGE_DRIVER=r2 when ready)
R2_ACCOUNT_ID=
R2_ACCESS_KEY_ID=
R2_SECRET_ACCESS_KEY=
R2_BUCKET=
R2_PUBLIC_URL=

# --- Web / Auth.js (Google sign-in) ---
AUTH_SECRET=${authSecret}
AUTH_TRUST_HOST=true
AUTH_GOOGLE_ID=
AUTH_GOOGLE_SECRET=

# --- Support email (optional) ---
SUPPORT_INBOX=support@${domain}
SUPPORT_FROM_EMAIL=FjordSend <noreply@${domain}>
RESEND_API_KEY=
SUPPORT_WEBHOOK_URL=
`;

writeFileSync(outPath, env, 'utf8');

console.log('Created .env.production');
console.log('');
console.log('Next steps:');
console.log('  1. Edit .env.production — set DOMAIN, ACME_EMAIL, AUTH_GOOGLE_ID, AUTH_GOOGLE_SECRET');
console.log(`  2. Point DNS: ${domain} and api.${domain} → your server IP`);
console.log(`  3. Google OAuth redirect: ${webUrl}/auth/callback/google`);
console.log('  4. Install Docker, then run: npm run docker:prod:up');
console.log('');
console.log('Database credentials (saved in .env.production):');
console.log(`  User:     ${postgresUser}`);
console.log(`  Database: ${postgresDb}`);
console.log(`  Password: ${postgresPassword}`);
